name: Coverage Report

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          python -m pip install tox

    - name: Run tests and generate coverage report
      run: |
        tox -e coverage
